Report deploy to rollbar
bodyshopbidsdotcom/PyRollbarAPI pull request #1
Opened 2018-08-29 17:04 UTC by jeet4320

2018-08-29 19:17 UTC, santi-h approved these changes

2018-08-30 13:47 UTC, santi-h requested changes
[We need to update the version to `0.7`](https://github.com/bodyshopbidsdotcom/PyRollbarAPI/blob/20309e12e209fbe4e0b80e518a2057520b98538e/setup.py#L3)

2018-09-04 20:52 UTC, whatisdot approved these changes

2018-09-04 20:53 UTC, whatisdot commented
@santi-h The update has been applied. Can we use the `git_deploy` similar to git-scripts?

2018-09-04 20:55 UTC, santi-h approved these changes

2018-09-04 20:55 UTC, merged